version: '2'
services:
  logstash:
    image: mt1-lrw.travelline.lan:5000/logstash
    environment:
      CA_CERTIFICATES_JAVA_VERSION: 20170531+nmu1
      GOSU_VERSION: '1.10'
      JAVA_DEBIAN_VERSION: 8u131-b11-2
      JAVA_HOME: /docker-java-home/jre
      JAVA_VERSION: 8u131
      LANG: C.UTF-8
      LOGSTASH_DEB_VERSION: 1:5.5.0-1
      LOGSTASH_VERSION: 5.5.0
      LS_SETTINGS_DIR: /etc/logstash
      PATH: /usr/share/logstash/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    entrypoint:
    - /docker-entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    ports:
    - 5044:5044/tcp
    command:
    - logstash
    - -f
    - /conf/
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  elasticsearch:
    image: mt1-lrw.travelline.lan:5000/elasticsearch
    environment:
      CA_CERTIFICATES_JAVA_VERSION: 20170531+nmu1
      ELASTICSEARCH_DEB_VERSION: 5.5.0
      ELASTICSEARCH_VERSION: 5.5.0
      GOSU_VERSION: '1.10'
      JAVA_DEBIAN_VERSION: 8u131-b11-2
      JAVA_HOME: /docker-java-home/jre
      JAVA_VERSION: 8u131
      LANG: C.UTF-8
      PATH: /usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    working_dir: /usr/share/elasticsearch
    entrypoint:
    - /docker-entrypoint.sh
    links:
    - kibana:kibana
    ports:
    - 9200:9200/tcp
    - 9300:9300/tcp
    command:
    - elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  nginx:
    image: mt1-lrw.travelline.lan:5000/nginx
    environment:
      NGINX_VERSION: 1.13.1-1~stretch
      NJS_VERSION: 1.13.1.0.1.10-1~stretch
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
    - /var/log/nginx:/var/log/nginx/
    - /var/log/nginx:/etc/logs/nginx/
    domainname: mt1-lrw.travelline.lan
    links:
    - db:database
    ports:
    - 80:80/tcp
    command:
    - nginx
    - -g
    - daemon off;
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
      io.rancher.container.network: 'true'
  filebeatnginx:
    image: mt1-lrw.travelline.lan:5000/filebeatnginx
    environment:
      ELASTIC_CONTAINER: 'true'
      PATH: /usr/share/filebeat:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    stdin_open: true
    working_dir: /usr/share/filebeat
    volumes:
    - /var/log/nginx:/etc/logs/nginx/
    - /var/log/nginx:/var/log/nginx/
    tty: true
    links:
    - logstash:logstash
    command:
    - filebeat
    - -e
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  filebeatapache:
    image: mt1-lrw.travelline.lan:5000/filebeatapache
    environment:
      ELASTIC_CONTAINER: 'true'
      PATH: /usr/share/filebeat:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    stdin_open: true
    working_dir: /usr/share/filebeat
    volumes:
    - /var/log/apache:/var/log/apache2/
    tty: true
    links:
    - logstash:logstash
    command:
    - filebeat
    - -e
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  php:
    image: mt1-lrw.travelline.lan:5000/apache
    environment:
      APACHE_LOCK_DIR: /var/lock/apache2
      APACHE_LOG_DIR: /var/log/apache2
      APACHE_PID_FILE: /var/run/apache2.pid
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_USER: www-data
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
    - /var/log/apache:/var/log/apache2/
    links:
    - db:database
    ports:
    - 9000:80/tcp
    command:
    - /bin/sh
    - -c
    - /usr/sbin/apache2ctl -D FOREGROUND
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  dbmain:
    image: mt1-lrw.travelline.lan:5000/mariadb
    environment:
      GOSU_VERSION: '1.7'
      GPG_KEYS: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB 430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A 4D1BB29D63D98E422B2113B19334A25F8507EFA5
      MARIADB_MAJOR: '10.1'
      MARIADB_VERSION: 10.1.24+maria-1~jessie
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    stdin_open: true
    entrypoint:
    - docker-entrypoint.sh
    domainname: mt1-lrw.travelline.lan
    tty: true
    ports:
    - 3306:3306/tcp
    - 4444:4444/tcp
    - 4567:4567/tcp
    - 4568:4568/tcp
    command:
    - mysqld
    - --wsrep-new-cluster
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: name=main
  kibana:
    image: mt1-lrw.travelline.lan:5000/kibana
    environment:
      GOSU_VERSION: '1.10'
      KIBANA_VERSION: 5.5.0
      PATH: /usr/share/kibana/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      TINI_VERSION: v0.9.0
    entrypoint:
    - /docker-entrypoint.sh
    links:
    - elasticsearch:elasticsearch
    ports:
    - 5601:5601/tcp
    command:
    - kibana
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  db:
    image: mt1-lrw.travelline.lan:5000/mariadb
    environment:
      GOSU_VERSION: '1.7'
      GPG_KEYS: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB 430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A 4D1BB29D63D98E422B2113B19334A25F8507EFA5
      MARIADB_MAJOR: '10.1'
      MARIADB_VERSION: 10.1.24+maria-1~jessie
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    stdin_open: true
    entrypoint:
    - docker-entrypoint.sh
    domainname: mt1-lrw.travelline.lan
    tty: true
    ports:
    - 3306:3306/tcp
    - 4444:4444/tcp
    - 4567:4567/tcp
    - 4568:4568/tcp
    command:
    - mysqld
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: name=main
      io.rancher.scheduler.global: 'true'

